name: Central Sync Close

on:
  push:
    branches: [ spring-integration ]






jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Request close promotion repo
      - uses: jvalkeal/nexus-sync@v0.0.2
        with:
          url: ${{ secrets.OSSRH_URL }}
          username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
          password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
          staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
          staging-repo-id: ${{ github.event.inputs.stagedRepositoryId }}
          close: true
