# Create the CI Sanity Check entry even when we only have ignored files
name: Quarkus CI Sanity Check

on:
  push:
    branches: [ quarkus ]

























jobs:
  ci-sanity-check:
    name: "CI Sanity Check"
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus'
    steps:
      - name: Build
        run: sleep 1
