name: CI
on:
  push:
    branches: [ vertx-web ]











jobs:
  Test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Run tests
        run: mvn -s .github/maven-ci-settings.xml clean verify -B
