name: Gradle wrapper validation
on:
  push:
    branches: [ opentelemetry-java ]







jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1.1.0
