# This workflow will build a Java project with Gradle
  push:
    branches: [ graph-data-science ]
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

permissions:
  contents: read
  issues: read
  pull-requests: read
  statuses: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run cipr task
        run: ./gradlew cipr --continue
