name: Compatibility Build

on:
  push:
    branches: [ spring-modulith ]




jobs:
  integration:
    strategy:
      matrix:
        version: ['3.0.9', '3.0.10-SNAPSHOT', '3.1.3-SNAPSHOT', '3.2.0-M1', '3.2.0-SNAPSHOT']
    name: Build against Boot ${{ matrix.version }}
    runs-on: ubuntu-latest

    steps:

    - name: Check out sources
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw -B -Pwith-preview-repos -Dspring-boot.version=${{ matrix.version }}
