name: PR build Play images for smoke tests

on:
  push:
    branches: [ opentelemetry-java-instrumentation ]





jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:play"
      cache-read-only: true
      # Play doesn't support Java 16+ yet
      # https://github.com/playframework/playframework/pull/10819
      skip-java-17: true
      skip-java-19: true
