name: quarkus-github-bot.yml lint

on:
  push:
    branches: [ quarkus ]







jobs:
  lint:
    name: "quarkus-github-bot.yml validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install yamllint
        shell: bash
        run: sudo apt-get install -y yamllint
      - name: run yamllint for quarkus-github-bot.yml
        shell: bash
        run: yamllint -c .github/yamllint.conf .github/quarkus-github-bot.yml
