name: Reusable - Muzzle

on:
  push:
    branches: [ opentelemetry-java-instrumentation ]






jobs:
  muzzle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ":instrumentation:muzzle1"
          - ":instrumentation:muzzle2"
          - ":instrumentation:muzzle3"
          - ":instrumentation:muzzle4"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17.0.6

      - name: Run muzzle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.task }}
          cache-read-only: ${{ inputs.cache-read-only }}
