# Perform a snapshot build and deploy to snapshot repository
# Notes
# - cannot run on Windows, as we use shell scripts

name: "Snapshot Release"

on:
  push:
    branches: [ helidon ]











jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Build and deploy
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
          RELEASE_WORKFLOW: "true"
        run: |
          etc/scripts/release.sh deploy_snapshot
