name: 'Run tests with Selenium nightly build'
on:
  push:
    branches: [ selenide ]



jobs:
  run-tests-on-linux:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: [ 'check', 'chrome_headless_smoke' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: '17'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.gradle-task }} -PseleniumVersionNightlyBuild=4.13.0-SNAPSHOT --no-parallel --no-daemon --console=plain
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-linux-${{matrix.gradle-task}}
          retention-days: 14
          path: |
            **/build/reports
            **/build/test-results
