name: Validate Gradle Wrapper
  push:
    branches: [ opensearch ]
on: [pull_request]

jobs:
  validate:
    name: Validate
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
