name: year
on:
  push:
    branches: [ eo ]





jobs:
  license:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: | #add new path with glob pattern https://www.npmjs.com/package/glob
            **/LICENSE.txt
            **/*.xml
            **/*.xsl
            **/*.java
            **/*.eo
            **/*.groovy
          commitTitle: "update license year"
